add deprecation notice in advance of archiving repo
ethereum/homestead-guide pull request #476
Opened 2022-05-12 13:54 UTC by jmcook1186

The relevant material from ethdocs.org has been migrated over to ethereum.org, enabling ethdocs.org to be sunsetted without losing the valuable information it contains. This PR simply adds a short deprecation notice to the README alerting readers to the imminent deprecation of ethdocs.org.

Relates to issue 5731 in ethereum.org repo [here](https://github.com/ethereum/ethereum-org-website/issues/5731)

2022-05-13 18:05 UTC, minimalsm approved these changes
LGTM

2022-05-16 08:09 UTC, samajammin commented on README.rst
>  ================================================================================
```suggestion
================================================================================

Looking to contribute to Ethereum documentation? Check out the ethereum.org repo: https://github.com/ethereum/ethereum-org-website

```

2022-05-16 08:10 UTC, samajammin commented on README.rst
>  HOW YOU CAN HELP
Perhaps we should remove the other sections on "HOW YOU CAN HELP"? e.g. I don't think we should push people to "Write Content to the Guide" or "Review What Has Been Written".

I suggested a note to push folks to the e.org repo.

2022-05-16 08:11 UTC, samajammin requested changes
LGTM! Suggested a couple small updates.

2022-05-16 16:58 UTC, merged